<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Serilog" Version="4.4.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\CoreLibraryCleanAdditionalService\Core.Library.Clean.AdditionalService.csproj" />
	</ItemGroup>
</Project>
